### ISSUE TITLE
Network with GaussianNoise layer cannot be converted

### ISSUE THREAD

**Issue by fmannhardt** [onnx/keras-onnx#111]
If have a model with a GaussianNoise layer that I want to convert, but this causes the following error:

```
WARNING:tensorflow:From /opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-06-10 11:33:53.303150: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-10 11:33:53.310936: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2388870000 Hz
2019-06-10 11:33:53.311172: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5578a1584ca0 executing computations on platform Host. Devices:
2019-06-10 11:33:53.311304: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/subgraph.py:124: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.remove_training_nodes
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'gaussian_noise/cond/random_normal/mean': Unknown input node '^gaussian_noise/cond/switch_t'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/convert.py", line 17, in <module>
    onnx_model = keras2onnx.convert_keras(keras_model, name=None, doc_string='', target_opset=9, channel_first_inputs=None)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/main.py", line 92, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/parser.py", line 497, in parse_graph
    return _parse_graph_scope(graph, keras_op_table, topo, top_level, output_names)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/parser.py", line 473, in _parse_graph_scope
    _convert_general_scope(nodes, varset)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/parser.py", line 204, in _convert_general_scope
    subgraph, replacement = create_subgraph(sess.graph, node_list, sess, operator.full_name)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/keras2onnx/subgraph.py", line 132, in create_subgraph
    tf.import_graph_def(output_graph_def, name=im_scope)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Node 'gaussian_noise/cond/random_normal/mean': Unknown input node '^gaussian_noise/cond/switch_t'
```

Will try to create a smaller network as example. I am using the latest Github code and Tensorflow 1.13.1

**Comment by jiafatom** [comment]
This [fix](https://github.com/onnx/keras-onnx/pull/129) is merged, does it resolve your issue?

**Comment by fmannhardt** [comment]
This is a different issue. The 'GaussianNoise' layer of Keras is not converted as it seems to be missing.

**Comment by jiafatom** [comment]
I missed the last message, just checked in the [fix](https://github.com/onnx/keras-onnx/pull/265), can you pull keras-onnx master and try?
