### ISSUE TITLE
Keras-onnx fails to convert LSTM with Sequence Length None

### ISSUE THREAD

**Issue by sonu1-p** [onnx/keras-onnx#134]
Its quite common in models to have sequence length variable, which is represented as by dim size None in Keras. When we convert such model using the converter, below error is seen:

```
Traceback (most recent call last):
  File "convert_as_is.py", line 13, in <module>
    onnx_model = keras2onnx.convert_keras(model, target_opset=10)
  File "/Users/sasa/k2e/keras-onnx/keras2onnx/main.py", line 99, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/Users/sasa/k2e/keras-onnx/keras2onnx/topology.py", line 231, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/Users/sasa/k2e/keras-onnx/keras2onnx/ke2onnx/lstm.py", line 163, in convert_keras_lstm
    desired_shape=[-1, seq_length, hidden_size])
  File "/Users/sasa/venv/lib/python3.6/site-packages/onnxconverter_common-1.5.0-py3.6.egg/onnxconverter_common/onnx_ops.py", line 451, in apply_reshape
    container.add_initializer(desired_shape_name, onnx_proto.TensorProto.INT64, [len(desired_shape)], desired_shape)
  File "/Users/sasa/k2e/keras-onnx/keras2onnx/common/interim.py", line 202, in add_initializer
    tensor = helper.make_tensor(name, onnx_type, shape, content)
  File "/Users/sasa/venv/lib/python3.6/site-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: None has type NoneType, but expected one of: int, long
```

Example LSTM Model for which the issue is reproducible can be created as:
```
import keras2onnx
from keras.models import Model
from keras.layers import Input, LSTM

lstm_dim = 2
stateful = True
inp = Input(batch_shape=(1, None, 1))
out = LSTM(lstm_dim, return_sequences=True, stateful=True)(inp)
model = Model(inputs=inp, outputs=out)

model.save("keras_2_custom_weights.h5")
onnx_model = keras2onnx.convert_keras(model, target_opset=10)
```

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/136), it should work now. Please pull latest master and try, thanks.

**Comment by sonu1-p** [comment]
Thank you so much jiafatom@ for the quick fix! This is super useful feature to have!!!
