### ISSUE TITLE
Conversion to ONNX creates invalid model

### ISSUE THREAD

**Issue by paulbauriegel** [onnx/keras-onnx#170]
I have a keras model that I want to be convert into ONNX. The conversion runs without errors, but the resulting model is not valid.
#### System environment
keras2onnx: 1.5.0
tensorflow: 1.14.0
python: 3.7.3
#### Problem
- [facenet_keras.h5](https://drive.google.com/open?id=1LqA_gII-1cIwwxwuRov2mrf4_g0hEy1D)
```python
import onnx
import keras2onnx
from keras.models import load_model

model_filename = 'facenet_keras.h5'
model = load_model(model_filename)

# Convert it!
onnx_model = keras2onnx.convert_keras(model, model.name)
onnx.save_model(onnx_model, 'facenet.onnx')

# Check it!
onnx.checker.check_model(onnx_model)
``` 
returns:
```
Traceback (most recent call last):
  File "onnx_keras.py", line 14, in <module>
    onnx.checker.check_model(onnx_model)
  File "/home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Block35_1_Branch_0_Conv2d_1x1_Activation_Relu_0' of node: 
input: "Block35_1_Branch_0_Conv2d_1x1_Activation_Relu_0" output: "Block35_1_Branch_0_Conv2d_1x1_BatchNorm_cond_Merge_0" name: "Transpose33" op_type: "Transpose" attribute { name: "perm" ints: 0 ints: 2 ints: 3 ints: 1 type: INTS } doc_string: "" domain: ""
 is not output of any previous nodes.
```

**Comment by jiafatom** [comment]
@paulbauriegel I just test this model on the latest keras2onnx master and it works successfully. We have done many changes since keras2onnx 1.5.0. Can you pull the master and try?

**Comment by paulbauriegel** [comment]
@jiafatom I just updated to keras2onnx version 1.5.1 and the Validation Error keeps the same. 

```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Bottleneck_BatchNorm/cond/Merge:01' of node: 
input: "Bottleneck_BatchNorm/cond/Merge:01" output: "Bottleneck_BatchNorm/cond/Merge:0" name: "Identity1" op_type: "Identity" domain: ""
 is not output of any previous nodes.
```

<details>
  <summary>Complete Log</summary>
  ```
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0727 19:32:25.002849 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0727 19:32:25.061403 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0727 19:32:25.080362 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0727 19:32:25.080534 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0727 19:32:25.080651 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-07-27 19:32:25.080895: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-27 19:32:25.111547: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-07-27 19:32:25.112073: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555a396763a0 executing computations on platform Host. Devices:
2019-07-27 19:32:25.112104: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-27 19:32:25.117607: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-07-27 19:32:25.150691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-27 19:32:25.151153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
2019-07-27 19:32:25.151396: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.151551: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.151651: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.151748: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.151867: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.151979: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-07-27 19:32:25.156328: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-07-27 19:32:25.156368: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-07-27 19:32:25.229609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-27 19:32:25.229661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-07-27 19:32:25.229675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-07-27 19:32:25.239644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-27 19:32:25.240289: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555a3c315b80 executing computations on platform CUDA. Devices:
2019-07-27 19:32:25.240321: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1050, Compute Capability 6.1
2019-07-27 19:32:25.277448: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
W0727 19:32:25.280954 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

W0727 19:32:25.555823 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0727 19:32:37.730500 140026423650112 deprecation.py:506] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
W0727 19:32:45.490185 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0727 19:32:45.490392 140026423650112 deprecation_wrapper.py:119] From /home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.WARN is deprecated. Please use tf.compat.v1.logging.WARN instead.

I0727 19:32:50.391195 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.391328 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.399582 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.399722 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.407001 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.407140 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.415373 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.415538 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.425292 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.425445 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.434185 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.434338 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.442165 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.442366 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.452548 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.452775 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.463444 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.463589 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.472312 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.472442 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.485567 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.485763 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.494037 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.494222 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.502408 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.502543 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.513240 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.513419 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.524217 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.524392 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.534932 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.535062 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.542789 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.542933 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.553354 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.553539 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.565254 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.565436 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.574431 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.574566 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.583787 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.583920 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
I0727 19:32:50.593034 140026423650112 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0727 19:32:50.593214 140026423650112 tfonnx.py:478] Using opset <onnx, 10>
Traceback (most recent call last):
  File "onnx_keras.py", line 13, in <module>
    onnx.checker.check_model(onnx_model)
  File "/home/paul/anaconda3/envs/tf/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Bottleneck_BatchNorm/cond/Merge:01' of node: 
input: "Bottleneck_BatchNorm/cond/Merge:01" output: "Bottleneck_BatchNorm/cond/Merge:0" name: "Identity1" op_type: "Identity" domain: ""
 is not output of any previous nodes.
  ```
</details>
/home/paul/Downloads

**Comment by jiafatom** [comment]
Seems like an onnxruntime bug? Do you use onnxruntime to run the model? Can you pull onnxruntime master? 
Also can you use onnxconverter-common 1.5.2 to keep the latest optimization code (this should not matter, but good to try).

**Comment by paulbauriegel** [comment]
@jiafatom It seems to work with the onnxruntime, but it fails on all other inference engines or tools it tried so far because of that. Described the details at the [issue](https://github.com/onnx/onnx/issues/1920) you mentioned.

**Comment by jiafatom** [comment]
@paulbauriegel Just checked in the fix in onnxconverter_common, can you pull its master and try? We will release pypi package soon.

**Comment by paulbauriegel** [comment]
@jiafatom Just tried you patch, works perfect. Thank you.

**Comment by jiafatom** [comment]
onnxconverter-common 1.5.3 is released.

**Comment by judrew** [comment]
Setting debug=False as in #537 helped in my case.
