### ISSUE TITLE
Error converting nested models

### ISSUE THREAD

**Issue by reymondzzzz** [onnx/keras-onnx#186]
tf version: 1.14.0
keras2onnx version: 1.5.1
onnx version: 1.5.0

Hi,

I want to convert nested keras model
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ['TF_KERAS'] = '1'

import tensorflow as tf
import tensorflow.keras.models as KM
import tensorflow.keras.layers as KL
import tensorflow.keras.backend as K

import keras2onnx
import onnxruntime
import numpy as np

if __name__ == '__main__':
    def _conv_layer(input, filters, kernel_size, strides=1, dilation_rate=1):
        padding = 'same' if strides == 1 else 'valid'
        if strides > 1:
            input = KL.ZeroPadding2D(((0, 1), (0, 1)), data_format=K.image_data_format())(input)
        x = KL.Conv2D(filters=filters, kernel_size=kernel_size, strides=strides,
                      padding=padding, use_bias=False, dilation_rate=dilation_rate)(input)
        ch_axis = 1 if K.image_data_format() == 'channels_first' else -1
        x = KL.BatchNormalization(axis=ch_axis)(x)
        return KL.ReLU()(x)

    def _model():
        input = KL.Input(shape=(3, 320, 320), name='input_1')
        x = _conv_layer(input, 16, 3)
        return KM.Model(inputs=input, outputs=x, name='backbone')

    # it not working 
    # first option
    input = KL.Input(shape=(3, 320, 320), name='input')
    backbone = _model()
    x = backbone(input)
    x = _conv_layer(x, 16, 3)
    model = KM.Model(inputs=[input], outputs=[x])
    model.summary()

    # it working
    # second option
    # backbone = _model()
    # x = _conv_layer(backbone.outputs[0], 16, 3)
    # model = KM.Model(inputs=backbone.inputs, outputs=[x])
    # model.summary()

    onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=7)
```

I want to save backbone weights separate. Second option doesn't allow this.
```
WARNING: Logging before flag parsing goes to stderr.
W0806 19:33:01.146663 4634232256 deprecation.py:506] From /Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           [(None, 3, 320, 320)]     0         
_________________________________________________________________
backbone (Model)             (None, 3, 320, 16)        46144     
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 3, 320, 16)        2304      
_________________________________________________________________
batch_normalization_1 (Batch (None, 3, 320, 16)        64        
_________________________________________________________________
re_lu_1 (ReLU)               (None, 3, 320, 16)        0         
=================================================================
Total params: 48,512
Trainable params: 48,448
Non-trainable params: 64
_________________________________________________________________
W0806 19:33:01.367336 4634232256 deprecation_wrapper.py:119] From /Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0806 19:33:01.367556 4634232256 deprecation_wrapper.py:119] From /Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/common/utils.py:42: The name tf.logging.WARN is deprecated. Please use tf.compat.v1.logging.WARN instead.

Traceback (most recent call last):
  File "/Users/kirillstarkov/Downloads/freeze_model_to_onnx.py", line 48, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=7)
  File "/Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/main.py", line 100, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/parser.py", line 649, in parse_graph
    return _parse_graph_scope(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "/Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/parser.py", line 601, in _parse_graph_scope
    _convert_keras_scope(graph, nodes, layer_key_, model_, varset)
  File "/Users/kirillstarkov/py_envs/ml/lib/python3.7/site-packages/keras2onnx/parser.py", line 179, in _convert_keras_scope
    assert len(node_list) == 0 or node_list[0] in [ts_.op for ts_ in outputs]
AssertionError

Process finished with exit code 1
```

Look's like method build_opdict_from_keras (keras2onnx/ke2onnx/main.py) matches  layer to model not corrects. keras_layer_ts_map(keras2onnx/parser.py) has 2 same records(backbone/conv2_1/const and conv2_1/const). I think problem in this place  :)

**Comment by jiafatom** [comment]
@reymondzzzz This issue is the same as the issue [here](https://github.com/onnx/keras-onnx/issues/179). I have checked in the fix, so please pull latest keras2onnx master and try again.

**Comment by reymondzzzz** [comment]
@jiafatom Thanks. keras2onnx from master works, but I have problem likes #188

**Comment by reymondzzzz** [comment]
With onnxconverter-common 1.5.3 is not work.

**Comment by jiafatom** [comment]
Your case is in our unit test [here](https://github.com/onnx/keras-onnx/blob/ccddaa683e79bb5026f4390f41c099d1677a537b/tests/test_layers.py) and it passes unit test every day. Do you pull latest keras2onnx master?

**Comment by reymondzzzz** [comment]
@jiafatom 
I used release version keras2onnx. On master working. When will be release?
And I noticed that the indentation conversion is not correct from Conv2D(same and valid). Final model has different output shape between onnx and keras. I can create new issue for this.

**Comment by jiafatom** [comment]
We plan to release the new version today. I want to cut off the release by 12:00 pm today PST. 
Please create a new issue if the output shape is different between onnx and keras. If this is a critical concern, we can postpone the release.
