### ISSUE TITLE
Conversion with tf.keras not working

### ISSUE THREAD

**Issue by letmaik** [onnx/keras-onnx#200]
```
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    linear_regression()
  File "test.py", line 79, in linear_regression
    onnx_model = keras2onnx.convert_keras(model)
  File "/home/.../miniconda3/lib/python3.7/site-packages/keras2onnx/main.py", line 103, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/.../miniconda3/lib/python3.7/site-packages/keras2onnx/topology.py", line 225, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/home/.../miniconda3/lib/python3.7/site-packages/keras2onnx/ke2onnx/dense.py", line 39, in convert_keras_dense
    apply_activation_function = activation_map[operator.raw_operator.activation]
KeyError: <function relu at 0x7f3f000da6a8>
```

The script is the tutorial from https://www.tensorflow.org/tutorials/keras/basic_regression.

Tested with:
tensorflow 1.13.1 and 1.14.0
keras2onnx 1.5.1
onnx==1.5.0
onnxconverter-common==1.5.3

I also tried with `TF_KERAS=1` but that didn't make a difference.

**Comment by letmaik** [comment]
Replacing  `activation=tf.nn.relu` with `activation='relu'` fixes it, but this should not be required.

**Comment by jiafatom** [comment]
Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/202) and it should work. Please pull keras2onnx master and try again.
