### ISSUE TITLE
Error in converting Keras model with custom layer to ONNX

### ISSUE THREAD

**Issue by shabnamrashtchi** [onnx/keras-onnx#212]
Hi 
I am trying to **convert my Keras model to ONNX.**
My model is Bidirectional LSTM with Self Attention layer. Attention class is a custom layer I developed for my Keas model. 
When I try to covert the model to ONNX I face the following error: 
I tried a few options: 
 ---loading keras model first: 
---AttentionLayer is the name of my class ( developed layer)
best_model = load_model( 'model.h5', custom_objects={'AttentionLayer': AttentionLayer})

onnx_model = onnxmltools.convert_keras(best_model, best_model.name)
----or 
import keras2onnx
onnx_model = keras2onnx.convert_keras(model, model.name
                                      , target_opset=7,
                                      debug_mode=False)

---or 
onnx.save(onnx_model, 'model.onnx')

``````````````````````````````````````````
Error: 
I0827 13:04:23.197570 140736254743424 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0827 13:04:23.197653 140736254743424 tfonnx.py:478] Using opset <onnx, 10>
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 32, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/main.py", line 103, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/topology.py", line 225, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/_builtin.py", line 23, in convert_reshape_timedistributed
    operator_name=operator.raw_operator.name, desired_shape=target_shape)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxconverter_common/onnx_ops.py", line 480, in apply_reshape
    container.add_initializer(desired_shape_name, onnx_proto.TensorProto.INT64, [len(desired_shape)], desired_shape)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/common/interim.py", line 205, in add_initializer
    tensor = helper.make_tensor(name, onnx_type, shape, content)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxmltools/proto/__init__.py", line 44, in _make_tensor_fixed
    getattr(tensor, field).extend(vals)
TypeError: None has type NoneType, but expected one of: int, long

**Comment by shabnamrashtchi** [comment]
Hi 
Thanks for getting back to me. Here is part of my model script.

MAX_LEN = None
EMBEDDING_DIM = 300
drop_rate = 0.4
n_units = 50
my_loss = 'categorical_crossentropy'

reduce = \
    ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=3, mode='auto')
early = \
    EarlyStopping(monitor='val_loss', min_delta=1e-4, patience=8, mode='auto')
checkpoint = ModelCheckpoint(codes_of_block[0] + '_HAN.h5', verbose=1,
                             monitor='val_loss',
                             save_best_only=True,
                             mode='auto')

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~SEN Encoder

# SENTENCE LEVEL

sent_ints = Input(shape=(None,))
sent_wv = Embedding(embedding_matrix.shape[0],
                    embedding_matrix.shape[1],
                    weights=[embedding_matrix],
                    input_length=MAX_LEN,
                    trainable=False)(sent_ints)

sent_wv_dr = Dropout(drop_rate)(sent_wv)

if GPU:
    sent_wa = Bidirectional(LSTM(units=50, return_sequences=True),
                            merge_mode='concat', weights=None)(sent_wv_dr)
else:
    sent_wa = Bidirectional(LSTM(units=50, return_sequences=True),
                            merge_mode='concat', weights=None)(sent_wv_dr)

sent_att_vec, sent_att_coeffs = \
    AttentionLayer(return_coefficients=True)(sent_wa)
sent_att_vec_dr = Dropout(drop_rate)(sent_att_vec)
sent_encoder = Model(sent_ints, sent_att_vec_dr)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~DOC Encoder

doc_ints = Input(shape=(None, None,))
sent_att_vecs_dr = TimeDistributed(sent_encoder)(doc_ints)
if GPU:
    doc_sa = Bidirectional(LSTM(units=50, return_sequences=True),
                           merge_mode='concat', weights=None)(sent_att_vecs_dr)
else:
    doc_sa = Bidirectional(LSTM(units=50, return_sequences=True),
                           merge_mode='concat', weights=None)(sent_att_vecs_dr)

doc_att_vec, doc_att_coeffs = AttentionLayer(return_coefficients=True)(doc_sa)
doc_att_vec_dr = Dropout(drop_rate)(doc_att_vec)

n_cats = np.shape(y_train)[1]
preds = Dense(units=n_cats,
              activation='softmax')(doc_att_vec_dr)

han = Model(doc_ints, preds)
han.save_weights('han_init_weights')
adam_optimizer = optimizers.Adam(lr=0.01, clipnorm=0.15)
han.compile(loss=my_loss,
            optimizer=adam_optimizer,
            metrics=['accuracy'])


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ Split train data set to:     train and test
X_train_test, X_val, Y_train_test, Y_val = train_test_split(X_train, y_train,
                                                            test_size=0.10,
                                                            random_state=7)
X_train, X_test, Y_train, Y_test = train_test_split(X_train_test,
                                                    Y_train_test,
                                                    test_size=0.2,
                                                    random_state=7)
history = han.fit(X_train, Y_train,
                  batch_size=1024,
                  epochs=20,
                  validation_data=(X_test, Y_test),
                  callbacks=[reduce, early, checkpoint])
han.summary()

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ Model Eval
plot_history(history)

# LOAD BEST MODEL AND RUN PREDICTIONS AND METRICS

best_model = load_model(codes_of_block[0] + '_HAN.h5', custom_objects={'AttentionLayer': AttentionLayer})
predicted_y_val = best_model.predict(X_val)

# CONVERT AND SAVE MODEL IN ONNX FORMAT

onnx_model = keras2onnx.convert_keras(best_model, best_model.name)
# onnx_model = onnxmltools.convert_keras(best_model)
onnx.save(onnx_model, 'model.onnx')
print('onnx model saved!!!!!')

**Comment by jiafatom** [comment]
Thanks for this. The code looks very long. which `self.attention_type` breaks? Just want to find a simple example that causes failure.

**Comment by jiafatom** [comment]
I debugged this and found two issues:
(1) TimeDistributed layer currently does not support dynamic shape for its internal reshape layer. 
(2) The TimeDistributed layer wraps a submodel which contains a custom layer `time_distributed_1/attention_layer_1`, in this case it is not supported.

**Comment by shabnamrashtchi** [comment]
Thanks for the debugging  and reply.

**Comment by jiafatom** [comment]
In this case we need convert the keras model to frozen tensorflow model first and then convert using tensorflow2onnx. I tried this but still fails, just raise an issue [there](https://github.com/onnx/tensorflow-onnx/issues/711)

**Comment by shabnamrashtchi** [comment]
Ok , I will. Thanks for the support.
