### ISSUE TITLE
Problem with onnxmltools.convert_keras using Models with Custom layer

### ISSUE THREAD

**Issue by shabnamrashtchi** [onnx/keras-onnx#225]
Hi 
I am trying to **convert my Keras model to ONNX.**
My model is Bidirectional LSTM with Self Attention layer. Attention class is a custom layer I developed for my Keas model. 
When I try to covert the model to ONNX I face the following error: 
I tried a few options: 
 ---loading keras model first: 
---AttentionLayer is the name of my class ( developed layer)
best_model = load_model( 'model.h5', custom_objects={'AttentionLayer': AttentionLayer})

onnx_model = onnxmltools.convert_keras(best_model, best_model.name)
----or 
import keras2onnx
onnx_model = keras2onnx.convert_keras(model, model.name
                                      , target_opset=7,
                                      debug_mode=False)

---or 
onnx.save(onnx_model, 'model.onnx')

``````````````````````````````````````````
Error: 
I0827 13:04:23.197570 140736254743424 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.2/0c735a
I0827 13:04:23.197653 140736254743424 tfonnx.py:478] Using opset <onnx, 10>
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxmltools/convert/main.py", line 32, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/main.py", line 103, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/topology.py", line 225, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/_builtin.py", line 23, in convert_reshape_timedistributed
    operator_name=operator.raw_operator.name, desired_shape=target_shape)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxconverter_common/onnx_ops.py", line 480, in apply_reshape
    container.add_initializer(desired_shape_name, onnx_proto.TensorProto.INT64, [len(desired_shape)], desired_shape)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/keras2onnx/common/interim.py", line 205, in add_initializer
    tensor = helper.make_tensor(name, onnx_type, shape, content)
  File "/Users/srashtchi001/Documents/code/project-coda/coda-tensorflow-test-0001-training/venv/lib/python3.7/site-packages/onnxmltools/proto/__init__.py", line 44, in _make_tensor_fixed
    getattr(tensor, field).extend(vals)
TypeError: None has type NoneType, but expected one of: int, long

**Comment by wenbingl** [comment]
it looks there is some unsupported data type during the conversion, can you share us more detail about the model?

**Comment by jiafatom** [comment]
Is this the same issue with [here](https://github.com/onnx/keras-onnx/issues/212)?

**Comment by jiafatom** [comment]
This is the same issue of [here](https://github.com/onnx/keras-onnx/issues/212), merge these two.
