### ISSUE TITLE
"IndexError: list index out of range" - while converting trained retinanet .h5 to onnx

### ISSUE THREAD

**Issue by PushkarChatterji** [onnx/keras-onnx#233]
Hi,
I have implemented transfer-learning on my own dataset on a retinanet model in keras.

When I try to convert this to an onnx file I get this error:
"IndexError: list index out of range"

my code is:

```
import keras
from keras_retinanet import models
import keras2onnx
import onnxruntime
import onnx

model_path = "/home/Projects/Documents/AI_models/resnet50_csv_20.h5"
ResNetModel = models.load_model(model_path, backbone_name = "resnet50")
onnx_model = keras2onnx.convert_keras(ResNetModel, ResNetModel.name)
onnx.save_model(onnx_model, "/home/Projects/Documents/AI_models/resnet50_csv_24_infer.onnx")
```

The full error message is:

```
Traceback (most recent call last):
  File "keras_resnet_model_to_onnx.py", line 24, in <module>
    onnx_model = keras2onnx.convert_keras(ResNetModel, ResNetModel.name)
  File "/home/Projects/.local/lib/python3.6/site-packages/keras2onnx/main.py", line 102, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/home/Projects/.local/lib/python3.6/site-packages/keras2onnx/parser.py", line 668, in parse_graph
    return _parse_graph_scope(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "/home/Projects/.local/lib/python3.6/site-packages/keras2onnx/parser.py", line 627, in _parse_graph_scope
    _infer_graph_shape(topology, top_scope, varset)
  File "/home/Projects/.local/lib/python3.6/site-packages/keras2onnx/parser.py", line 390, in _infer_graph_shape
    _finalize_tf2onnx_op(topology, oop, varset)
  File "/home/Projects/.local/lib/python3.6/site-packages/keras2onnx/parser.py", line 354, in _finalize_tf2onnx_op
    ov = varset.get_local_variable_or_declare_one(nodes[n0_][i_], _infer_variable_type(n_, varset.target_opset))
IndexError: list index out of range
```

Any pointers on how I can fix this?

Thanks!

**Comment by mdztravelling** [comment]
I have the save problem when convert keras_retinanet to onnx, how to solve it?

  File "convert_onnx.py", line 12, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/home/ssd1/work/test/keras-onnx-master/keras2onnx/main.py", line 102, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/home/ssd1/work/test/keras-onnx-master/keras2onnx/parser.py", line 668, in parse_graph
    return _parse_graph_scope(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "/home/ssd1/work/test/keras-onnx-master/keras2onnx/parser.py", line 627, in _parse_graph_scope
    _infer_graph_shape(topology, top_scope, varset)
  File "/home/ssd1/work/test/keras-onnx-master/keras2onnx/parser.py", line 390, in _infer_graph_shape
    _finalize_tf2onnx_op(topology, oop, varset)
  File "/home/ssd1/work/test/keras-onnx-master/keras2onnx/parser.py", line 354, in _finalize_tf2onnx_op
    ov = varset.get_local_variable_or_declare_one(nodes[n0_][i_], _infer_variable_type(n_, varset.target_opset))
IndexError: list index out of range

**Comment by jiafatom** [comment]
Can you share the model please?

**Comment by PushkarChatterji** [comment]
here you go...

[https://www.dropbox.com/s/isc4fc65tn2cjx1/resnet50_csv_20.h5?dl=0](url)

**Comment by jiafatom** [comment]
I made the [fix](https://github.com/onnx/keras-onnx/pull/247) to resolve this error. Now the model can be converted. But when run with onnxruntime, it got the error that the nodes in Loop node are not topologically sorted. This bug happens in tf2onnx converter which we uses to convert custom layers. It may take time to fix this...

**Comment by CHONGCHUANSHENG** [comment]
@jiafatom  hello i didn't understand  how to operate " IndexError: list index out of range"problem by  your fix. could u have a  rough description that how fix it? many thanks

**Comment by jiafatom** [comment]
@CHONGCHUANSHENG just pull the latest keras2onnx master, and then install it. When you convert, you need `onnx_model = keras2onnx.convert_keras(model.keras_model, target_opset=10, custom_op_conversions=tf2onnx_contrib_op_conversion)` to enable `tf2onnx_contrib_op_conversion`, just like `test_mask_rcnn` (we will have some refactoring to move `tf2onnx_contrib_op_conversion`, though).

**Comment by CHONGCHUANSHENG** [comment]
@jiafatom  okay  thanks for your help.  I will keep an eye on your developments in time.

**Comment by PushkarChatterji** [comment]
@jiafatom Thanks for coming back in this. 

I'll close the issue for now. 

Any timelines on when the onnxruntime will be able to run this?
