### ISSUE TITLE
Tensor is unhashable if Tensor equality is enabled with the tf2 branch on tf2-gpu-rc1

### ISSUE THREAD

**Issue by philvanzu** [onnx/keras-onnx#251]
```
Traceback (most recent call last):
  File "D:/dev/DeepVPy/deepV_main.py", line 39, in <module>
    onnx_model = onnxmltools.convert_keras(model, target_opset=7)
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\site-packages\onnxmltools\convert\main.py", line 32, in convert_keras
    return convert(model, name, doc_string, target_opset, channel_first_inputs)
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\keras2onnx\main.py", line 101, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names)
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\keras2onnx\parser.py", line 669, in parse_graph
    return _parse_graph_scope(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\keras2onnx\parser.py", line 568, in _parse_graph_scope
    keras_nodeset = _build_keras_nodeset(inference_nodeset, keras_node_dict)
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\keras2onnx\parser.py", line 506, in _build_keras_nodeset
    nodes.update(_create_keras_nodelist(layer_, inference_nodeset))
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\keras2onnx\parser.py", line 451, in _create_keras_nodelist
    ts_end |= set(list_input_tensors(node_))
  File "C:\Users\philippe\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 713, in __hash__
    raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```

here's the model detail
```

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 224, 224, 16)      448       
_________________________________________________________________
activation (Activation)      (None, 224, 224, 16)      0         
_________________________________________________________________
batch_normalization (BatchNo (None, 224, 224, 16)      64        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 16)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 112, 112, 32)      4640      
_________________________________________________________________
activation_1 (Activation)    (None, 112, 112, 32)      0         
_________________________________________________________________
batch_normalization_1 (Batch (None, 112, 112, 32)      128       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 56, 56, 64)        18496     
_________________________________________________________________
activation_2 (Activation)    (None, 56, 56, 64)        0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 56, 56, 64)        256       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 50176)             0         
_________________________________________________________________
dense (Dense)                (None, 16)                802832    
_________________________________________________________________
activation_3 (Activation)    (None, 16)                0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 51        
=================================================================
```
 or is this a tf2 bug that has nothing to do with keras2onnx?

**Comment by philvanzu** [comment]
sorry I posted too fast... I'm such a novice with python.
I dowgraded to beta1 tf build and the issue is gone
