### ISSUE TITLE
Network with GaussianNoise layer cannot be converted

### ISSUE THREAD

**Issue by dkloving** [onnx/keras-onnx#264]
It seems that the gaussian noise node is unable to be converted. Also see #111 

>I1003 13:44:06.208431  9168 tfonnx.py:475] Using tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.5.3/7b598d
I1003 13:44:06.208431  9168 tfonnx.py:478] Using opset <onnx, 10>
Exception on this tf.graph
TFNodes/gaussian_noise_1/cond/random_normal/mean
TFNodes/gaussian_noise_1/cond/random_normal/stddev
TFNodes/gaussian_noise_1_input
TFNodes/keras_learning_phase
TFNodes/gaussian_noise_1/cond/pred_id
TFNodes/gaussian_noise_1/cond/Switch_1
TFNodes/gaussian_noise_1/cond/Shape/Switch
TFNodes/gaussian_noise_1/cond/Shape
TFNodes/gaussian_noise_1/cond/random_normal/RandomStandardNormal
TFNodes/gaussian_noise_1/cond/random_normal/mul
TFNodes/gaussian_noise_1/cond/random_normal
TFNodes/gaussian_noise_1/cond/add
TFNodes/gaussian_noise_1/cond/Merge
TFNodes_identity
TFNodes_identity_1
W1003 13:44:06.222444  9168 wrapper.py:31] Exception on this tf.graph
TFNodes/gaussian_noise_1/cond/random_normal/mean
TFNodes/gaussian_noise_1/cond/random_normal/stddev
TFNodes/gaussian_noise_1_input
TFNodes/keras_learning_phase
TFNodes/gaussian_noise_1/cond/pred_id
TFNodes/gaussian_noise_1/cond/Switch_1
TFNodes/gaussian_noise_1/cond/Shape/Switch
TFNodes/gaussian_noise_1/cond/Shape
TFNodes/gaussian_noise_1/cond/random_normal/RandomStandardNormal
TFNodes/gaussian_noise_1/cond/random_normal/mul
TFNodes/gaussian_noise_1/cond/random_normal
TFNodes/gaussian_noise_1/cond/add
TFNodes/gaussian_noise_1/cond/Merge
TFNodes_identity
TFNodes_identity_1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\anaconda36\lib\site-packages\keras2onnx\main.py", line 98, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "c:\anaconda36\lib\site-packages\keras2onnx\parser.py", line 736, in parse_graph
    return _parse_graph_scope(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "c:\anaconda36\lib\site-packages\keras2onnx\parser.py", line 695, in _parse_graph_scope
    _infer_graph_shape(topology, top_scope, varset)
  File "c:\anaconda36\lib\site-packages\keras2onnx\parser.py", line 458, in _infer_graph_shape
    _finalize_tf2onnx_op(topology, oop, varset)
  File "c:\anaconda36\lib\site-packages\keras2onnx\parser.py", line 428, in _finalize_tf2onnx_op
    g = tf2onnx_wrap(topo, subgraph, outputs, varset.target_opset)
  File "c:\anaconda36\lib\site-packages\keras2onnx\wrapper.py", line 32, in tf2onnx_wrap
    raise e
  File "c:\anaconda36\lib\site-packages\keras2onnx\wrapper.py", line 26, in tf2onnx_wrap
    output_names=outputs)
  File "c:\anaconda36\lib\site-packages\keras2onnx\ktf2onnx\tf2onnx\tfonnx.py", line 569, in process_tf_graph
    topological_sort(g, continue_on_error)
  File "c:\anaconda36\lib\site-packages\keras2onnx\ktf2onnx\tf2onnx\tfonnx.py", line 407, in topological_sort
    g.topological_sort(ops)
  File "c:\anaconda36\lib\site-packages\keras2onnx\ktf2onnx\tf2onnx\graph.py", line 835, in topological_sort
    utils.make_sure(j is not None, "Cannot find node with output {}".format(inp))
  File "c:\anaconda36\lib\site-packages\keras2onnx\ktf2onnx\tf2onnx\utils.py", line 290, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Cannot find node with output TFNodes/gaussian_noise_1/cond/Merge:1

**Comment by jiafatom** [comment]
just checked in the [fix](https://github.com/onnx/keras-onnx/pull/265), can you pull keras-onnx master and try?

**Comment by dkloving** [comment]
Yes, this works. Thanks!
