### ISSUE TITLE
onnxruntime error for mask_RCNN

### ISSUE THREAD

**Issue by Benzidrine** [onnx/keras-onnx#270]
Attempting to use a fresh pull of keras-onnx master doesn't appear to be able to create a valid onnx model for mask_rcnn. 

I tried using the standard matterport/Mask_RCNN/mask_rcnn_coco.h5 and my own retrained models.

I received the following error in all cases. 

**Error:**

There is an error(<class 'AssertionError'>) happened during optimizing on the converted model!
Traceback (most recent call last):
  File "mask_rcnn.py", line 732, in <module>
    sess = onnxruntime.InferenceSession(model_file_name)
  File "C:\ProgramData\Anaconda3\envs\KerasToOnnx\lib\site-packages\onnxruntime\capi\session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from ./mrcnn.onnx failed:This is an invalid model. Node (Identity99) input arg (rpn_model/lambda_1/Reshape:0) does not have type information set by parent node.

**version list**

keras                     2.2.4                         0
keras-applications        1.0.8                      py_0
keras-base                2.2.4                    py37_0
keras-preprocessing       1.1.0                      py_1
keras2onnx                1.6.0                    pypi_0    pypi
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
onnx                      1.6.0                    pypi_0    pypi
onnxconverter-common      1.5.5                    pypi_0    pypi
onnxruntime               0.5.0                    pypi_0    pypi
pip                       19.2.3                   py37_0
python                    3.7.4                h5263a28_0
scikit-image              0.15.0           py37ha925a31_0
tensorboard               1.14.0           py37he3c9ec2_0
tensorflow                1.14.0          mkl_py37h7908ca0_0
tensorflow-base           1.14.0          mkl_py37ha978198_0
tensorflow-estimator      1.14.0                     py_0

**Comment by Benzidrine** [comment]
Sorry I believe I worked out the issue was and it was a misunderstanding leading to a coding error on my part.
