### ISSUE TITLE
YoloV3 conversion

### ISSUE THREAD

**Issue by yonglizhong** [onnx/keras-onnx#287]
Hi all. I am interested in using the YOLOv3 Keras model to ONNX format. It is the one that is from https://github.com/qqwweee/keras-yolo3, which the attempt to convert has been successful. For personal interest, I would like to convert it once more with my own pretrained model. I've attempted to use the yolov3.py API but to no success. My first question is if you have the list of packages and their versions, I believe there might be a few dependencies problems for me. I am also wondering what is the difference between the yolov3.py & test_yolov3.py since yolov3.py suffices my needs. Thanks

**Comment by yonglizhong** [comment]
This is the command I've used

> python yolov3.py /home/lizhong/keras-yolo3/pictures/bus.jpg

**Comment by yonglizhong** [comment]
And the following are the packages I have installed.

> Package                Version  
---------------------- ---------
absl-py                0.8.1    
astor                  0.8.0    
atomicwrites           1.3.0    
attrs                  19.3.0   
bleach                 1.5.0    
cachetools             3.1.1    
certifi                2018.8.24
chardet                3.0.4    
coverage               4.5.4    
cycler                 0.10.0   
fire                   0.2.1    
gast                   0.2.2    
google-auth            1.7.0    
google-auth-oauthlib   0.4.1    
google-pasta           0.1.8    
grpcio                 1.24.3   
h5py                   2.10.0   
html5lib               0.9999999
idna                   2.8      
importlib-metadata     0.23     
Keras                  2.1.5    
Keras-Applications     1.0.8    
Keras-Preprocessing    1.1.0    
keras2onnx             1.6.0    
kiwisolver             1.1.0    
Markdown               3.1.1    
matplotlib             3.0.3    
more-itertools         7.2.0    
numpy                  1.17.3   
oauthlib               3.1.0    
onnx                   1.6.0    
onnxconverter-common   1.6.0    
onnxruntime            1.0.0    
opencv-python          4.1.1.26 
opt-einsum             3.1.0    
packaging              19.2     
pathlib2               2.3.5    
Pillow                 6.2.1    
pip                    19.3.1   
pluggy                 0.13.0   
protobuf               3.10.0   
py                     1.8.0    
pyasn1                 0.4.7    
pyasn1-modules         0.2.7    
pyparsing              2.4.3    
pytest                 5.2.2    
python-dateutil        2.8.1    
PyYAML                 5.1.2    
requests               2.22.0   
requests-oauthlib      1.2.0    
rsa                    4.0      
scipy                  1.3.1    
setuptools             41.6.0   
six                    1.12.0   
tensorboard            1.6.0    
tensorflow             1.5.0    
tensorflow-estimator   1.15.1   
tensorflow-tensorboard 1.5.1    
termcolor              1.1.0    
typing-extensions      3.7.4.1  
urllib3                1.25.6   
wcwidth                0.1.7    
Werkzeug               0.16.0   
wheel                  0.31.1   
wrapt                  1.11.2   
zipp                   0.6.0

**Comment by yonglizhong** [comment]
Duplicate of #121 I've also received the similar error, but opset is 10

**Comment by jiafatom** [comment]
Can you use keras 2.2.4+ and tensorflow 1.11.0+ ? `test_yolov3.py` is an end-to-end nightly build test (we run it every day to ensure correctness), but the core part is the same as `yolov3.py`. You just replace the .h5 file with your own file in `test_yolov3.py` , then it should work.

**Comment by mckhang** [comment]
Hello, I have tested with test_yolov3.py with yolov3 h5 file from https://github.com/qqwweee/keras-yolo3 but I keep getting the following error. Any advice on this matter?

2019-12-30 13:40:38.481690: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:38.482199: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
2019-12-30 13:40:38.989981: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:38.990532: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py:251: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if weight_names:
2019-12-30 13:40:40.373318: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:40.374380: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
2019-12-30 13:40:40.492524: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:40.494453: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
2019-12-30 13:40:40.607255: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:40.608198: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
2019-12-30 13:40:47.909061: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:47.909947: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
2019-12-30 13:40:48.295570: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:48.296692: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
2019-12-30 13:40:48.427660: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:2005] Running auto_mixed_precision graph optimizer
2019-12-30 13:40:48.428124: I tensorflow/core/grappler/optimizers/auto_mixed_precision.cc:1248] No whitelist ops found, nothing to do
../../../keras-yolo3/yolo3/../yolov3-tiny.h5 model, anchors, and classes loaded.
E
======================================================================
ERROR: test_yolov3 (__main__.TestYoloV3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_yolov3.py", line 81, in test_yolov3
    onnx_model = keras2onnx.convert_keras(my_yolo.final_model, channel_first_inputs=['input_1'])
  File "/workspace/keras-onnx/keras2onnx/main.py", line 63, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/workspace/keras-onnx/keras2onnx/topology.py", line 268, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/workspace/keras-onnx/keras2onnx/_builtin.py", line 591, in convert_tf_reshape
    desired_shape=shape_value)
  File "/workspace/keras-onnx/keras2onnx/common/onnx_ops.py", line 91, in apply_op_with_output
    apply_func(self._scope, ox_inputs, outputs, self._container, operator_name=name, **attrs)
  File "/usr/local/lib/python3.5/dist-packages/onnxconverter_common/onnx_ops.py", line 565, in apply_reshape
    container.add_node('Reshape', [input_name, desired_shape_name], output_name, op_version=5, name=name)
  File "/workspace/keras-onnx/keras2onnx/common/interim.py", line 117, in add_node
    raise ValueError('Inputs must be a list of string but get [%s]' % type_list)
ValueError: Inputs must be a list of string but get [<class 'list'>,<class 'str'>]

----------------------------------------------------------------------
Ran 1 test in 14.102s

FAILED (errors=1)

**Comment by mckhang** [comment]
Hello, I have tested with test_yolov3.py with yolov3 h5 file from https://github.com/qqwweee/keras-yolo3 but I keep getting the following error. Any advice on this matter?

![Screen Shot 2019-12-30 at 10 46 16 PM](https://user-images.githubusercontent.com/37468544/71584526-456a5600-2b56-11ea-8c28-7696e930e5dd.jpg)

**Comment by jiafatom** [comment]
@mckhang can you pull latest keras2onnx master and onnxconverter-common master and try?

**Comment by jiafatom** [comment]
keras2onnx 1.6.5 just released, please have a try.
