### ISSUE TITLE
IndexError when use_bias is set to False

### ISSUE THREAD

**Issue by srikanthderebail** [onnx/keras-onnx#35]
I am trying to convert this simple Keras model to onnx.
model = Sequential()
model.add(Dense(32, activation='relu', use_bias = False, input_dim=100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
onnx_model = keras2onnx.convert_keras(model, model.name)

But when I run the code, I get this error.

Traceback (most recent call last):
  File "onnx_example.py", line 28, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "C:\Users\mfuzb1\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\main.py", line 109, in convert_keras
    debug_mode, custom_op_conversions)
  File "C:\Users\mfuzb1\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\main.py", line 80, in _convert_tf
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "C:\Users\mfuzb1\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\topology.py", line 234, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "C:\Users\mfuzb1\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\ke2onnx\dense.py", line 38, in convert_keras_dense
    bias = parameters[1]
IndexError: list index out of range

The error is not thrown when use_bias = True. Is it mandatory to provide bias parameters in the model ?? 

Thanks in advance for the help,
Srikanth

**Comment by jiafatom** [comment]
@srikanthderebail I just checked in the [fix](https://github.com/onnx/keras-onnx/pull/36) , please try again.

**Comment by srikanthderebail** [comment]
Yes, the error is fixed. 
Thanks!!
