### ISSUE TITLE
support for tf.math.add_n

### ISSUE THREAD

**Issue by jusonn** [onnx/keras-onnx#401]
tensorflow-onnx supports tf.math.add and tf.math.add_n in https://github.com/onnx/tensorflow-onnx/blob/master/support_status.md but keras-onnx doesn't

 when I convert AddN, an error occurs
```
node lambda/AddN of type AddN cannot be converted, fall back to tf2onnx
Traceback (most recent call last):
  File "build_model.py", line 66, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/main.py", line 60, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 794, in parse_graph
    graph, keras_node_dict, topo, top_level, output_names)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 595, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 335, in _on_parsing_tf_subgraph
    raise RuntimeError("Some tensorflow operation doesn't support, stop converting.")
RuntimeError: Some tensorflow operation doesn't support, stop converting.
```
since tf-onnx supports AddN, it can be easily supported in keras-onnx https://github.com/onnx/tensorflow-onnx/blob/ed3a41d91146116ab789b285be4fe86d56cc5004/tf2onnx/onnx_opset/reduction.py

**Comment by wenbingl** [comment]
@jiafatom

**Comment by jiafatom** [comment]
The [PR](https://github.com/onnx/keras-onnx/pull/406) is checked in, please pull keras2onnx master and try.
