### ISSUE TITLE
Keras2onnx converter fails to convert tf.split node

### ISSUE THREAD

**Issue by sonu1-p** [onnx/keras-onnx#431]
I wanted to convert a keras model that was using tf.split node to ONNX. I get this error on doing so:
```
Traceback (most recent call last):
  File "test2.py", line 9, in <module>
    onnx_model = keras2onnx.convert_keras(model, target_opset=11)
  File "/Users/spareek/venv/lib/python3.6/site-packages/keras2onnx/main.py", line 94, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names)
  File "/Users/spareek/venv/lib/python3.6/site-packages/keras2onnx/parser.py", line 835, in parse_graph
    return _parse_graph_core(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "/Users/spareek/venv/lib/python3.6/site-packages/keras2onnx/parser.py", line 752, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/Users/spareek/venv/lib/python3.6/site-packages/keras2onnx/parser.py", line 404, in _on_parsing_tf_subgraph
    subgraph, replacement = create_subgraph(graph, node_list, sess, operator.full_name)
  File "/Users/spareek/venv/lib/python3.6/site-packages/keras2onnx/subgraph.py", line 173, in create_subgraph
    tf.import_graph_def(output_graph_def, name=im_scope)
  File "/Users/spareek/venv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/spareek/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/Users/spareek/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'Squeeze': Connecting to invalid output 1 of source node split which has 1 outputs.
```

I was able to reproduce the same issue with this simple model:
```
import tensorflow as tf
import keras2onnx

x = tf.keras.Input(shape=(1, 12), dtype="int32", name="input")
x1,x2,x3 = tf.split(x,[3,1,8], axis=2)
p = tf.squeeze(x2)
model = tf.keras.Model(inputs=x, outputs=[p], name="test2")
model.save("split.h5")
onnx_model = keras2onnx.convert_keras(model, target_opset=11)
```
Can you please help look into this. Please let me know if you need any more information from me.

**Comment by sonu1-p** [comment]
The issue got resolved by installing keras2onnx from latest source. Resolving.
