### ISSUE TITLE
I try to remove the identity block,but faild

### ISSUE THREAD

**Issue by KingerFzb** [onnx/keras-onnx#436]
`import onnx
from onnx import optimizer
import keras2onnx
from keras.models import load_model
import onnxmltools

model = load_model('mobile_allgraph_v1.h5',compile=False)

onnx_model = onnxmltools.convert_keras(model,model.name)
#去掉identity层
all_passes = optimizer.get_available_passes()
print("Available optimization passes:")
for p in all_passes:
print('\t{}'.format(p))

onnx_optimized = 'mobilenet_optimized.onnx'
passes = ['eliminate_identity']
optimized_model = optimizer.optimize(onnx_model, passes)
onnx.save(optimized_model, onnx_optimized)
`
I try to remove the identity,but faild
Uploading image.png…

Traceback (most recent call last): File "modify_onnx.py", line 18, in <module> optimized_model = optimizer.optimize(onnx_model, passes) File "D:\Anaconda3\envs\tensorflow36\lib\site-packages\onnx\optimizer.py", line 55, in optimize optimized_model_str = C.optimize(model_str, passes) IndexError: invalid unordered_map<K, T> key

**Comment by jiafatom** [comment]
(1) This is onnx optimizer, so you need raise issue in onnx repo, not here.
(2) Our keras2onnx converter has its own optimizer which is powerful, so you don't need this optimization step.
