### ISSUE TITLE
RNN model with initial state as an input

### ISSUE THREAD

**Issue by srikanthderebail** [onnx/keras-onnx#46]
Hello,

I am trying to save a keras model to onnx format. Here is the model specification:
input = Input(shape=(1,2))
state = Input(shape=(5,))
hidden_1 = SimpleRNN(5, activation='relu',return_sequences=True)(input,initial_state=[state])
output = Dense(2, activation='sigmoid')(hidden_1)
model = Model(inputs=[input,state],outputs=output)
The initial state is also an input in the model.  I get the following error when I try to convert the model to onnx:

Traceback (most recent call last):
  File "gradient_rnn.py", line 44, in <module>
    onnx_model = keras2onnx.convert_keras(model_new)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\main.py", line 96, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\topology.py", line 232, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\ke2onnx\simplernn.py", line 31, in convert_keras_simple_rnn
    container.add_initializer(tensor_w_name, onnx_proto.TensorProto.FLOAT, [1, hidden_size, input_size], W.flatten())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\keras2onnx\common\interim.py", line 202, in add_initializer
    tensor = helper.make_tensor(name, onnx_type, shape, content)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\onnx\helper.py", line 175, in make_tensor
    tensor.dims.extend(dims)
TypeError: (None, 10) has type tuple, but expected one of: int, long

Thank you for the help in advance :)

**Comment by jiafatom** [comment]
@srikanthderebail just made the [fix](https://github.com/onnx/keras-onnx/commit/a67b3ab0434dcb621c66610adb979fa05695da63) and checked in, please try again, thank you!

**Comment by srikanthderebail** [comment]
It works!! Thanks a lot.
