### ISSUE TITLE
ValueError: Value "<dtype: 'float32'>" is not valid attribute data type.

### ISSUE THREAD

**Issue by dimabendera** [onnx/keras-onnx#481]
when I run 
```bash
python mask_rcnn.py 1045023827_4ec3e8ba5c_z.jpg
```
I got Error:
```
Traceback (most recent call last):
  File "mask_rcnn.py", line 723, in <module>
    oml = keras2onnx.convert_keras(model.keras_model, target_opset=11)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/main.py", line 92, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/parser.py", line 828, in parse_graph
    return _parse_graph_core(graph, keras_layer_ts_map, topo, top_level, output_names)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/parser.py", line 756, in _parse_graph_core
    _infer_graph_shape(topology, top_scope, varset)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/parser.py", line 479, in _infer_graph_shape
    _finalize_tf2onnx_op(topology, oop, varset)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/parser.py", line 449, in _finalize_tf2onnx_op
    g = tf2onnx_wrap(topo, subgraph, outputs, varset.target_opset)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/wrapper.py", line 357, in tf2onnx_wrap
    raise e
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/wrapper.py", line 351, in tf2onnx_wrap
    output_names=outputs)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/ktf2onnx/tf2onnx/tfonnx.py", line 493, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/ktf2onnx/tf2onnx/tfonnx.py", line 122, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/usr/local/lib/python3.7/site-packages/keras2onnx/ktf2onnx/tf2onnx/tfonnx.py", line 109, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/usr/local/lib64/python3.7/site-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib64/python3.7/site-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/usr/local/lib64/python3.7/site-packages/onnx/helper.py", line 273, in make_attribute
    'Value "{}" is not valid attribute data type.'.format(value))
ValueError: Value "<dtype: 'float32'>" is not valid attribute data type.
```

Python 3.7.7
tensorflow 1.15.2

**Comment by dimabendera** [comment]
install from source help:

```bash
pip install git+https://github.com/microsoft/onnxconverter-common
pip install git+https://github.com/onnx/keras-onnx
```
