### ISSUE TITLE
AttributeError: module 'keras2onnx' has no attribute 'convert_keras'

### ISSUE THREAD

**Issue by wuxiaolianggit** [onnx/keras-onnx#524]
AttributeError: module 'keras2onnx' has no attribute 'convert_keras'
Excuse me, how to solve this problem？ @shinh

**Comment by jiafatom** [comment]
Did you search the issue history, for example [this](https://github.com/onnx/keras-onnx/issues/82)?

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply @jiafatom

**Comment by wuxiaolianggit** [comment]
There is an error(<class 'IndexError'>) happened during optimizing on the converted model!
list index out of range
Traceback (most recent call last):
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/keras2onnx/topology.py", line 345, in convert_topology
    target_opset=container.target_opset)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1761, in optimize_onnx_graph
    node_list = _process_optimization(node_list, target_opset)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1609, in _process_optimization
    temp_list, success = _apply_optimization(solution, node_list)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1586, in _apply_optimization
    return solution.apply(node_list)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1358, in apply
    cur_perm_map)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1290, in _process_transpose_pass_node
    cur_perm_map)
  File "/home/wuxiaoliang/.local/lib/python3.5/site-packages/onnxconverter_common/optimizer.py", line 1186, in _process_transpose_pass_broadcast
    init_pred_value = numpy_helper.to_array(prev.tensors[0])
IndexError: list index out of range

Excuse me, how to solve this problem？ @jiafatom

**Comment by jiafatom** [comment]
This should be an optimizer bug, can you share the model (or simplified model) for us to debug?

**Comment by wuxiaolianggit** [comment]
ok, The model is in Baidu cloud disk
link: https://pan.baidu.com/s/1ac8TJo1YXtBHobpcd32AIg extract: w9w5, @jiafatom

**Comment by jiafatom** [comment]
Just checked in the fix (see above), can you pull `onnxconverter-common` master and try it again?
