### ISSUE TITLE
Conversion of InstanceNormalization in combination with LSTM fails

### ISSUE THREAD

**Issue by breizhn** [onnx/keras-onnx#543]
Hi together,

I am trying to convert following model: (minimal example)
```python
import keras2onnx
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, LSTM, Input
import tensorflow_addons as tfa

in_dat = Input(batch_shape=[1,1,128])
x = tfa.layers.InstanceNormalization(axis=2, 
                                    center=True, 
                                    scale=True,
                                    beta_initializer="random_uniform",
                                    gamma_initializer="random_uniform")(in_dat)
x = LSTM(128, return_sequences=True, stateful=True)(x)
out_dat = Dense(128)(x)
model = Model(inputs=in_dat, outputs=out_dat)

onnx_model = keras2onnx.convert_keras(model)
```

this creates following error:
```bash
Traceback (most recent call last):
  File "test_model_script.py", line 16, in <module>
    test_class.convert_to_onnx()
  File "xx/xx/create_model_class.py", line 113, in convert_to_onnx
    onnx_model = keras2onnx.convert_keras(self.model)
  File "/home/xx/anaconda3/envs/tf22env/lib/python3.7/site-packages/keras2onnx/main.py", line 62, in convert_keras
    tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
  File "/home/xx/anaconda3/envs/tf22env/lib/python3.7/site-packages/keras2onnx/_parser_tf.py", line 302, in build_layer_output_from_model
    return extract_outputs_from_subclassing_model(model, output_dict, input_names, output_names)
  File "/home/xx/anaconda3/envs/tf22env/lib/python3.7/site-packages/keras2onnx/_parser_tf.py", line 264, in extract_outputs_from_subclassing_model
    concrete_func, lower_control_flow=True)
  File "/home/xxs/anaconda3/envs/tf22env/lib/python3.7/site-packages/keras2onnx/_graph_cvt.py", line 506, in convert_variables_to_constants_v2
    raise ValueError("Cannot find the Placeholder op that is an input "
ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.
```

Converting without the LSTM layer works fine:
```python
in_dat = Input(batch_shape=[1,1,128])
x = tfa.layers.InstanceNormalization(axis=2, 
                                    center=True, 
                                    scale=True,
                                    beta_initializer="random_uniform",
                                    gamma_initializer="random_uniform")(in_dat)

out_dat = Dense(128)(x)
model = Model(inputs=in_dat, outputs=out_dat)

onnx_model = keras2onnx.convert_keras(model)
```

What can I do? Is there a workaround? Or is it a Tensorflow bug?

Thanks for your help in advance!
Best,
Nils
(Ubuntu 18.04 / TF 2.1 / conda )

**Comment by jiafatom** [comment]
Why `x = LSTM(128, return_sequences=True, stateful=True)()` not `x = LSTM(128, return_sequences=True, stateful=True)(x)`?

**Comment by breizhn** [comment]
Oh the ```x``` got lost.

**Comment by breizhn** [comment]
Ok, when handling the states separately and setting the lstm to 
```python
LSTM(128, return_sequences=True, stateful=False, return_states=True, unroll=True)
``` 
the conversion works.

**Comment by breizhn** [comment]
Because I got it working, I close the issue.
