### ISSUE TITLE
Prediction on probability output of keras?

### ISSUE THREAD

**Issue by apremgeorge** [onnx/keras-onnx#547]
I have a keras model 
```
cols = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y']
payload = [[0.62382546,-0.37804684,-0.079906,-0.45980235,0.34740723,0.00235355,-0.29869863,-2.25137177,0.09773262,-0.04770562,-1.13753923,-2.31292707,0.27057148,-1.84923494,-0.65983332,0.07649027,-0.07734961,-0.70264886,0.17072499,0.1468576,-2.07244491,0.84444339,-0.05756989,-1.54643614,0.10969839]]
import pandas 
df = pandas.DataFrame(data=payload,columns=cols)
kerasmodel.predict_proba(df.values)
```
the model return
```
array([[0.01505428]], dtype=float32)
```
Now I use onnx
```
onnx_model = keras2onnx.convert_keras(kerasmodel, 'keras-onnx', debug_mode=1)
keras2onnx.save_model(onnx_model, 'keras-onnx.onnx')

sess_options = onnxruntime.SessionOptions()
sess = onnxruntime.InferenceSession('keras-onnx.onnx', sess_options)
feed = dict([(input.name, payload[n]) for n, input in enumerate(sess.get_inputs())])
onnx_predicted_label = sess.run(None, feed)[0].argmax()
```
I get error
```
Traceback (most recent call last):

  File "<ipython-input-72-60dc3ed517ff>", line 1, in <module>
    onnx_predicted_label = sess.run(None, feed)[0].argmax()

  File "C:\Users\PremGeorgeAlphonse\Anaconda3\lib\site-packages\onnxruntime\capi\session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: dense_4_input Got: 1 Expected: 2 Please fix either the inputs or the model.
```
I am sure I am not doing the prediction with onnxruntime correctly? may I have some help, Thanks

one more question, If I import this onnx model and the payload in ML.NET, can I do the prediction there as well right?

**Comment by jiafatom** [comment]
We have many examples in running onnxruntime in this repo. Please check Readme or examples. If you just use `kerasmodel.predict`, can it work correctly on onnxruntime?

**Comment by apremgeorge** [comment]
Found it, I should have done the following
```
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx = sess.run([label_name], {input_name: payload})[0]
```
