### ISSUE TITLE
concatenating tensors give IndexError: list index out of range with opset 8

### ISSUE THREAD

**Issue by adder** [onnx/keras-onnx#550]
Hey

I use tensorflow 2.2 and keras2onnx installed from source.
When executing the following minimal code:

```
import tensorflow as tf
import keras2onnx
inp = tf.keras.layers.Input(shape=[480, 640, 6])

def custom_reduce(o):
    o1 = tf.reduce_max(o * [1,0,0,0,1,1],-1,keepdims = True)
    o2 = tf.reduce_max(o * [0,1,0,0,0,0],-1,keepdims = True)
    o3 = tf.reduce_max(o * [0,0,1,1,0,0],-1,keepdims = True)
    return tf.concat([o1,o2],-1)

# o = tf.keras.layers.Conv2D(6, (1, 1), activation='relu', padding='same')(inp)
o = tf.keras.layers.Softmax()(inp)
out = tf.keras.layers.Lambda(custom_reduce)(o)
m = tf.keras.Model(inp,out)
onnx_model = keras2onnx.convert_keras(m,target_opset = 8)
```
 I get the error

```
tf executing eager_mode: True
tf.keras model eager_mode: False
There is an error(<class 'IndexError'>) happened during optimizing on the converted model!
list index out of range
Traceback (most recent call last):
  File "/Users/adriaan/.pyenv/versions/tf22/lib/python3.7/site-packages/keras2onnx/topology.py", line 336, in convert_topology
    outputs=container.outputs)
  File "/Users/adriaan/.pyenv/versions/tf22/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 1714, in optimize_onnx
    node_list = _process_optimization(node_list, target_opset)
  File "/Users/adriaan/.pyenv/versions/tf22/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 1629, in _process_optimization
    solution = optm.find(node_)
  File "/Users/adriaan/.pyenv/versions/tf22/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 1535, in find
    if MergeCommonSequenceOptimizer.is_same_node_merge(succ_0, succ_1, node):
  File "/Users/adriaan/.pyenv/versions/tf22/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 1598, in is_same_node_merge
    val_0 = numpy_helper.to_array(pred_0.tensors[0])
IndexError: list index out of range
```

Any clues, why I get this error and how to get around it?
It works with opset version 9 but I'm stuck with 8 because of limitations downstream the pipline.
Thanks

**Comment by jiafatom** [comment]
Please pull latest `onnxconverter_common` master, we have a recent fix which resolves this issue.

**Comment by adder** [comment]
thanks
