### ISSUE TITLE
failing conversion for MaxPooling1D and AveragePooling1D

### ISSUE THREAD

**Issue by julianjungwirth** [onnx/keras-onnx#615]
Hi,
I found that trying to convert a very simple model that contains tf.keras.layers.MaxPooling1D fails with the following error:
```
Traceback (most recent call last):
  File "detection/signal_detection/conversion/tf2onnx.py", line 173, in <module>
    normalize_inputs=normalize_inputs, show_overlay=args.show_overlay)
  File "detection/signal_detection/conversion/tf2onnx.py", line 43, in main
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/home/julian/anaconda3/envs/py36_tf2.1/lib/python3.6/site-packages/keras2onnx/main.py", line 80, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/home/julian/anaconda3/envs/py36_tf2.1/lib/python3.6/site-packages/keras2onnx/parser.py", line 841, in parse_graph
    ) if is_tf2 and is_tf_keras else _parse_graph_core(
  File "/home/julian/anaconda3/envs/py36_tf2.1/lib/python3.6/site-packages/keras2onnx/parser.py", line 718, in _parse_graph_core_v2
    varset, visited, q_overall)
  File "/home/julian/anaconda3/envs/py36_tf2.1/lib/python3.6/site-packages/keras2onnx/parser.py", line 668, in _parse_nodes_v2
    {**keras_node_dict, **current_layer_outputs}, inference_nodeset)
  File "/home/julian/anaconda3/envs/py36_tf2.1/lib/python3.6/site-packages/keras2onnx/_parser_tf.py", line 130, in create
    if fstr_list is not None and i_.op.name.find(layer_name) == -1:
TypeError: must be str, not NoneType
```

**Code to reproduce:**

- tensorflow==2.2.0 or 2.3.0
- keras2onnx==1.7.0

```
import tensorflow as tf
import keras2onnx

# 1. build a simple model
inputs = tf.keras.layers.Input((256, 1))
x = inputs
x = tf.keras.layers.Conv1D(kernel_size=2, filters=16)(x)
x = tf.keras.layers.MaxPooling1D(pool_size=2, strides=2)(x)
x = tf.keras.layers.Conv1D(kernel_size=2, filters=16)(x)
outputs = x
model = tf.keras.models.Model(inputs, outputs, name='Model')
model.summary()

# 2. convert to ONNX
onnx_model = keras2onnx.convert_keras(model, model.name)
print('successfully converted model')
```

Interestingly, it works when using 2D-Pooling, just adding a dimension. It also works returning `tensor_type` `FloatTensorType` in _parser_tf.py instead of throwing the ValueError. 

Kind regards and thanks for the great work the keras2onnx-team puts in :+1:

**Comment by jiafatom** [comment]
Please try keras2onnx master branch not from pypi right now. Seems working to me.

**Comment by julianjungwirth** [comment]
@jiafatom, you are right. Installing keras2onnx==1.7.1 from source works out. Thanks.
