### ISSUE TITLE
Run into onnx validation error if a convolution layer does not have BN layer. 

### ISSUE THREAD

**Issue by Tyler-D** [onnx/keras-onnx#618]
Hi @jiafatom ,

I found an onnx model validation error when converting keras (tf.keras) model to onnx model using keras2onnx > 1.6.0 :
```
The ONNX operator number change on the optimization: 9 -> 4
The maximum opset needed by this model is only 6.
Traceback (most recent call last):
  File "debug_onnx.py", line 19, in <module>
    onnx.checker.check_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: conv2d/kernel:0 in initializer but not in graph input
```

The software environment I used :
```
keras2onnx>1.6.0 (I have tried 1.6.1, 1.7.0 and 1.7.1 from source code)
onnx==1.7.0
tensorflow-gpu==1.15.0
```

And the minimal reproducing sample is 
```
from tensorflow import keras
import onnx
import keras2onnx

import os
os.environ["TF_KERAS"]="1"

inputs = keras.layers.Input(shape=(32, 32, 3))
conv = keras.layers.Conv2D(16, (3, 3))(inputs)
# conv = keras.layers.BatchNormalization()(conv)
relu = keras.layers.Activation("relu", name="relu0")(conv)
keras_model = keras.models.Model(inputs=inputs, outputs=relu)

onnx_model = keras2onnx.convert_keras(keras_model)
onnx.checker.check_model(onnx_model)
```

For keras2onnx == 1.6.0, it will pass the `check_model` without error.

Thanks for your help.

**Comment by jiafatom** [comment]
Just checked in the fix [here](https://github.com/microsoft/onnxconverter-common/pull/146), please pull onnxconverter-common master branch and retry.

**Comment by Tyler-D** [comment]
Thanks @jiafatom. The fix works well.

Close the issue.
