### ISSUE TITLE
ValueError: There can only be one -1 in the targeted shape of a Reshape but got [-1, -1, 23542]

### ISSUE THREAD

**Issue by wyd12345** [onnx/keras-onnx#626]
hi there,
I am trying to convert a Keras model to ONXX on Ubuntu 18.04 and i had this error. any ideas what have i done wrong?
    
here is the output :

Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
2020-10-04 15:27:54.338166: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-04 15:27:54.338264: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> import keras2onnx
>>> import onnx
>>> from keras.models import load_model
>>> model = load_model('/home/wyd/文档/modeljxb.h5')
2020-10-04 15:31:18.094892: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-10-04 15:31:18.094940: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-04 15:31:18.094970: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (wyd-Lenovo-B40-70): /proc/driver/nvidia/version does not exist
2020-10-04 15:31:18.095373: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-04 15:31:18.126350: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1895600000 Hz
2020-10-04 15:31:18.127960: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55788d908690 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-04 15:31:18.128332: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-04 15:31:18.225596: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 96428032 exceeds 10% of free system memory.
2020-10-04 15:31:18.378792: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 96428032 exceeds 10% of free system memory.
2020-10-04 15:31:18.417076: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 96428032 exceeds 10% of free system memory.
2020-10-04 15:31:20.526316: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 96428032 exceeds 10% of free system memory.
2020-10-04 15:31:20.661112: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 96428032 exceeds 10% of free system memory.
>>> onnx_model = keras2onnx.convert_keras(model, model.name)
tf executing eager_mode: True
tf.keras model eager_mode: False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/main.py", line 83, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/topology.py", line 322, in convert_topology
    cvt(scope, operator, container)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/_builtin.py", line 1107, in convert_reshape_timedistributed
    operator_name=operator.full_name, desired_shape=target_shape)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/onnxconverter_common/onnx_ops.py", line 781, in apply_reshape
    raise ValueError('There can only be one -1 in the targeted shape of a Reshape but got %s' % desired_shape)
ValueError: There can only be one -1 in the targeted shape of a Reshape but got [-1, -1, 23542]
>>> onnx_model = keras2onnx.convert_keras(modeljxb.h5）
  File "<stdin>", line 1
    onnx_model = keras2onnx.convert_keras(modeljxb.h5）
                                                     ^
SyntaxError: invalid character in identifier
>>> onnx_model = keras2onnx.convert_keras(model, model.name)
tf executing eager_mode: True
tf.keras model eager_mode: False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/main.py", line 83, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/topology.py", line 322, in convert_topology
    cvt(scope, operator, container)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/keras2onnx/_builtin.py", line 1107, in convert_reshape_timedistributed
    operator_name=operator.full_name, desired_shape=target_shape)
  File "/home/wyd/.conda/envs/tensorflow1/lib/python3.7/site-packages/onnxconverter_common/onnx_ops.py", line 781, in apply_reshape
    raise ValueError('There can only be one -1 in the targeted shape of a Reshape but got %s' % desired_shape)
ValueError: There can only be one -1 in the targeted shape of a Reshape but got [-1, -1, 23542]

**Comment by jiafatom** [comment]
We had a recent fix on this issue. Please pull keras2onnx master and onnxconverter-common master and retry. (Check Readme if you don't know how to use keras2onnx from source).

**Comment by Lakshmisha-SN** [comment]
Hiii @jiafatom I have a similar problem can you guys tell me what I should do.

ValueError: There can only be one -1 in the targeted shape of a Reshape but got [-1, -1, 4]
