### ISSUE TITLE
KerasTensor object has no attribute 'graph'

### ISSUE THREAD

**Issue by za13** [onnx/keras-onnx#662]
I am using Ubuntu 18 and Tensorflow 2.5, ONNX 1.7, and Keras 2.4. I'm trying to convert Keras code to Onnx. I have the following Python code:

    from __future__ import print_function
    import warnings
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    from keras import backend as K
    from keras.callbacks import CSVLogger
    from keras.layers import *
    from keras.models import Model
    from keras.optimizers import Adam
    from scipy.io import loadmat
    from scipy.misc import imread
    from skimage.io import imsave
    from skimage.transform import resize
    from scipy.io import loadmat
    import cv2

    Ny=512	
    target_size = (Ny, Ny)
    warnings.filterwarnings('ignore')
    %matplotlib inline
    LR= 1e-5
    E, BS = 200,4 

    def get_unet(img_rows, img_cols):
        inputs = Input((img_rows, img_cols, 1))
        conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(inputs)
        conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv1)
        pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
        conv2 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool1)
        conv2 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv2)
        pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)
        conv3 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool2)
        conv3 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv3)
        pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)
        conv4 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool3)
        conv4 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv4)
        drop4 = Dropout(0.5)(conv4)
        pool4 = MaxPooling2D(pool_size=(2, 2))(drop4)
        conv5 = Conv2D(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool4)
        conv5 = Conv2D(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv5)
        drop5 = Dropout(0.5)(conv5)
        up6 = Conv2D(512, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(drop5))
        merge6 = concatenate([drop4,up6], axis = 3)
        conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge6)
        conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv6)
        up7 = Conv2D(256, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv6))
        merge7 = concatenate([conv3,up7], axis = 3)
        conv7 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge7)
        conv7 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv7)
        up8 = Conv2D(128, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv7))
        merge8 = concatenate([conv2,up8], axis = 3)
        conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge8)
        conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv8)
        up9 = Conv2D(64, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv8))
        merge9 = concatenate([conv1,up9], axis = 3)
        conv9 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge9)
        conv9 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv9)
        conv9 = Conv2D(2, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv9)
        conv10 = Conv2D(1, 1, activation = 'sigmoid')(conv9)

        model = Model(inputs=[inputs], outputs=[conv10])
        model.compile(optimizer=Adam(lr=LR), 
                          loss='binary_crossentropy', metrics=['binary_crossentropy'])
        return model

    outName='Unet'
    trainDir='train' 
    trainAnnotDir='trainannot'

    #training images
    import os
    Image_directory = './' + trainDir + '/'
    Label_directory = './' + trainAnnotDir + '/'

    image_lists = {os.path.basename(x[0]): x[2] for x in os.walk('./'+trainDir)}
    n = len(image_lists[trainDir])
    ids = os.listdir(trainDir)

    train_images=np.zeros([n, Ny,Ny,1], dtype=float)
    annot_train=np.zeros([n, Ny,Ny,1], dtype=float)
    for j in range(0, n):
        l=ids[j][:-4]
        img = cv2.imread(Image_directory+l+'.bmp', 0)/255.0 
        label = cv2.imread(Label_directory+l+'.bmp', 0)/255.0
        train_images[j,:,:,0], annot_train[j,:,:,0] =img, label

    #test images
    testDir='test'
    testAnnotDir='testannot'
    Image_directory = './' + testDir + '/'
    Label_directory = './' + testAnnotDir + '/'

    image_lists = {os.path.basename(x[0]): x[2] for x in os.walk('./'+testDir)}
    n = len(image_lists[testDir])#16
    ids = os.listdir(testDir)

    nTestTotal=21
    test_images=np.zeros([nTestTotal, Ny,Ny,1], dtype=float)
    annot_test=np.zeros([nTestTotal, Ny,Ny,1], dtype=float)
    nTest=0
    for j in range(0, n): #n):
        l=ids[j][:-4]
        img = cv2.imread(Image_directory+l+'.bmp',0)/255.0  
        label = cv2.imread(Label_directory+l+'.bmp',0)/255.0
        if img.shape[0]==Ny:
            test_images[nTest,:,:,0], annot_test[nTest,:,:,0] =img, label
            nTest+=1

    C = np.concatenate([annot_test, annot_train])
    I = np.concatenate([test_images, train_images])

    #mixed precision
    import tensorflow as tf
    from tensorflow.keras.mixed_precision import experimental as mixed_precision
    policy = mixed_precision.Policy('mixed_float16')
    mixed_precision.set_policy(policy)
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.compat.v1.Session(config=config)

    csv_callback = CSVLogger('history.log', append=True)
    unet = get_unet(Ny, Ny)

    filepath="W-E_{epoch:02d}-L_{loss:.6f}"+outName+".h5"
    callbacks = keras.callbacks.ModelCheckpoint('./'+filepath, monitor='loss', verbose=1,
        save_best_only=True, mode='min', period=1)

    history = unet.fit(I, C, verbose=2, epochs=E, batch_size=BS, validation_split=0.1, callbacks=[csv_callback])

    from tensorflow.keras.models import save_model
    save_model(unet, outName+'.keras')

I then tried to convert it to ONNX with this:

	from keras.models import load_model
	import onnx
	import keras2onnx
	import tensorflow as tf

	outName='Unet'
	E,BS,LR=200,4,1e-5
	Estr, LRstr='200', '0.00001'

	onnx_model_name = 'unetMaster.onnx'

	model = load_model(outName+'.keras')
	onnx_model = keras2onnx.convert_keras(model, model.name)
	onnx.save_model(onnx_model, onnx_model_name)

but it gave the error

	File "kerasToOnnx.py", line 15, in <module>
	    onnx_model = keras2onnx.convert_keras(model, model.name)
	  File "/home/me/.local/lib/python3.8/site-packages/keras2onnx/main.py", line 62, in convert_keras
	    tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
	  File "/home/me/.local/lib/python3.8/site-packages/keras2onnx/_parser_tf.py", line 304, in build_layer_output_from_model
	    graph = model.outputs[0].graph
	AttributeError: 'KerasTensor' object has no attribute 'graph'

maybe I'm getting this error because ONNX Only works with Tensorflow 1 instead of 2? can anyone help with this?

**Comment by jiafatom** [comment]
keras2onnx works for both tf 1 and 2. For tf2, when you load the model, it loads as tf.keras model by default. Is your model a keras one or tf.keras one? Can you try keras2onnx from master?

**Comment by za13** [comment]
It's keras and not tf.keras, right? How can I tell if its tf.keras?

I get the same error if I do `from tensorflow.keras.models import load_model` or `from keras.models import load_model`

and if I uninstall keras2onnx and install it with:

    pip install -U git+https://github.com/microsoft/onnxconverter-common
    pip install -U git+https://github.com/onnx/keras-onnx

and then attempt to load the keras model again, I get the same error

**Comment by za13** [comment]
can you answer my question please?

**Comment by knsatishkumar** [comment]
Facing same issue:-
Python 3.7.7
tensorflow 2.4.0
onnx 1.8.0
2.4.3

Error Message
AttributeError                            Traceback (most recent call last)
<ipython-input-13-2b713a0562b4> in <module>
      6 print(keras.__version__)
      7 
----> 8 onnx_model = onnxmltools.convert_keras(nn)
      9 
     10 onnxmltools.utils.save_model(onnx_model, 'keras_example.onnx')

\python\python37\lib\site-packages\onnxmltools\convert\main.py in convert_keras(model, name, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators, default_batch_size)
     31 
     32     from keras2onnx import convert_keras as convert
---> 33     return convert(model, name, doc_string, target_opset, channel_first_inputs)
     34 
     35 

\python\python37\lib\site-packages\keras2onnx\main.py in convert_keras(model, name, doc_string, target_opset, channel_first_inputs, debug_mode, custom_op_conversions)
     60     output_dict = {}
     61     if is_tf2 and is_tf_keras:
---> 62         tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
     63     else:
     64         tf_graph = model.outputs[0].graph if is_tf2 else keras.backend.get_session().graph

\python\python37\lib\site-packages\keras2onnx\_parser_tf.py in build_layer_output_from_model(model, output_dict, input_names, output_names)
    302         return extract_outputs_from_subclassing_model(model, output_dict, input_names, output_names)
    303     else:
--> 304         graph = model.outputs[0].graph
    305         output_names.extend([n.name for n in model.outputs])
    306         output_dict.update(extract_outputs_from_inbound_nodes(model))

AttributeError: 'KerasTensor' object has no attribute 'graph'

Code : 

`#!/usr/bin/env python
# coding: utf-8

# In[1]:


import keras


# In[2]:


from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)


# In[3]:


import matplotlib.pyplot as plt

n = 10

fig, ax = plt.subplots(1, n, figsize=(10, 2))
for idx, image in enumerate(train_images[:10]):
    ax[idx].imshow(image, cmap=plt.cm.Greys)
    ax[idx].set_xticks([])
    ax[idx].set_yticks([])
    ax[idx].set_title(train_labels[idx], fontsize=18)

plt.show()


# In[4]:


# Flatten images
train_images = train_images.reshape((60000, 28 * 28))
# Normalise images
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


# In[5]:


from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)


# In[6]:


from keras import models
from keras import layers

nn = models.Sequential()
nn.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
nn.add(layers.Dense(10, activation='softmax'))

nn.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])


# In[7]:


nn.fit(train_images, train_labels, epochs=5, batch_size=128)


# In[8]:


test_loss, test_accuracy = nn.evaluate(test_images, test_labels)

print('test_acc:', test_accuracy)


# In[9]:


import onnxmltools

onnx_model = onnxmltools.convert_keras(nn) 

onnxmltools.utils.save_model(onnx_model, 'keras_example.onnx')


# In[ ]:





`

**Comment by jiafatom** [comment]
Currently we don't support tensorflow 2.4.0, is it possible you downgrade to tf 2.3.0?

**Comment by luvwinnie** [comment]
Any progress on this issue?

**Comment by StefanStsc** [comment]
Has anyone a solution for this issue?
I've a Mac M1 and can only use Tensorflow 2.4

**Comment by o-11** [comment]
You have to downgrade your version of tensorflow. I was having this problem in google colab where the default version is currently 2.4.0. 
Try:
pip install tensorflow==2.2.0

**Comment by StefanStsc** [comment]
That doesn't really work. On mac M1 only TF 2.4. is available from Apple.
