### ISSUE TITLE
No onnx op 'embedding_lookup' and gelu_erf activation function 

### ISSUE THREAD

**Issue by floyddcn** [onnx/keras-onnx#674]
bert4keras                0.7.7                    
keras                     2.3.1                   
tensorflow 1.14.0
keras2onnx 1.7.0

i want to convert the simbert pretrained model to onnx format with following code:
`
bert = build_transformer_model(
    config_path,
    checkpoint_path,
    with_pool='linear',
    application='unilm',
    keep_tokens=keep_tokens,  # 只保留keep_tokens中的字，精简原字表
    return_keras_model=False,
)
encoder = keras.models.Model(bert.model.inputs, bert.model.outputs[0])
seq2seq = keras.models.Model(bert.model.inputs, bert.model.outputs[1])

outputs = TotalLoss([2, 3])(bert.model.inputs + bert.model.outputs)
model = keras.models.Model(bert.model.inputs, outputs)

onnx_model = keras2onnx.convert_keras(model, model.name)  
onnx.save_model(onnx_model, 'bert_model.onnx')`

but, i got some warning and error. Please help,thanks.
------------------------------------------------------------
WARN: No corresponding ONNX op matches the tf.op node Embedding-Token/embedding_lookup of type ResourceGather
      The generated ONNX model needs run with the custom op supports.
Traceback (most recent call last):
  File "D:\python\ide\PyCharm2020.2.3\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\python\ide\PyCharm2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/python/workspace/simbert/simbert-test.py", line 264, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)  
  File "D:\programs\miniconda3\envs\py36\lib\site-packages\keras2onnx\main.py", line 83, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "D:\programs\miniconda3\envs\py36\lib\site-packages\keras2onnx\topology.py", line 322, in convert_topology
    cvt(scope, operator, container)
  File "D:\programs\miniconda3\envs\py36\lib\site-packages\keras2onnx\ke2onnx\dense.py", line 43, in convert_keras_dense
    activation_process(scope, operator, container, biased_tensor_name)
  File "D:\programs\miniconda3\envs\py36\lib\site-packages\keras2onnx\ke2onnx\common.py", line 24, in activation_process
    apply_activation_function = activation_map[operator.raw_operator.activation]
KeyError: <function gelu_erf at 0x0000028A33256B70>
python-BaseException

**Comment by TyrionZK** [comment]
How do you resolved it finally? I face the same problem.
