### ISSUE TITLE
2 issues when using keras2onnx with all Pooling3D layers and BatchNormalization layer: TypeError: must be str, not NoneType, TypeError: value "" is not valid attribute data type.

### ISSUE THREAD

**Issue by navegeri** [onnx/keras-onnx#688]
Trying to save a trained keras 3D-Unet as an ONNX using keras2onnx.
here is the downsized code I created to investigate to errors.

```
# Define sub Unet convolution block
def conv3d_block(input_tensor, n_filters, kernel_size=3, batchnorm=True):
    # first layer
    x = Conv3D(filters=n_filters, kernel_size=(kernel_size, kernel_size, kernel_size), kernel_initializer="he_normal",
               padding="same")(input_tensor)
    if batchnorm:
        x = BatchNormalization()(x)
    x = Activation("relu")(x)
    # # second layer
    x = Conv3D(filters=n_filters, kernel_size=(kernel_size, kernel_size, kernel_size), kernel_initializer="he_normal",
               padding="same")(x)
    if batchnorm:
        x = BatchNormalization()(x)
    x = Activation("relu")(x)
    return x


# Define Vnet
def get_vnet(input_img, n_filters=16, dropout=0.5, is_batchnorm=True):
    c1 = conv3d_block(input_img, n_filters=n_filters * 1, kernel_size=3, batchnorm=is_batchnorm)
    p1 = Cropping3D(cropping=(128, 128, 2))(c1)
    # p1 = MaxPooling3D(pool_size=(2, 2, 2))(c1)
    p1 = Dropout(dropout)(p1)

    u9 = Conv3DTranspose(n_filters * 1, (3, 3, 3), strides=(2, 2, 2), padding='same')(p1)
    u9 = concatenate([u9, c1], axis=4)
    u9 = Dropout(dropout)(u9)
    c9 = conv3d_block(u9, n_filters=n_filters * 1, kernel_size=3, batchnorm=is_batchnorm)

    outputs = Conv3D(1, (1, 1, 1), activation='sigmoid')(c9)
    model = Model(inputs=[input_img], outputs=[outputs])
    return model


# Defining and compiling a new 3D V-NET model
def create_vnet_model(filters_number, dropout_factor, loss="binary_crossentropy", is_batchnorm=True,
                      learning_rate=0.001):
    # Define models and compile them
    input_image = Input((IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_3D_NUMBER, 1), name='imgs')
    model = get_vnet(input_image, n_filters=filters_number, dropout=dropout_factor, is_batchnorm=is_batchnorm)
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss=loss, metrics=["accuracy"])
    return model


model = create_vnet_model(8, 0.5, loss="binary_crossentropy", is_batchnorm=True,
                          learning_rate=0.001)
onnx_model = keras2onnx.convert_keras(model, debug_mode=1)
onnx.save_model(onnx_model, SAVE_PATH_MODEL + "onnx3dproblem" + ".onnx")
```

here is the summary of the model:
```
Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
imgs (InputLayer)               [(None, 512, 512, 8, 0                                            
__________________________________________________________________________________________________
conv3d (Conv3D)                 (None, 512, 512, 8,  224         imgs[0][0]                       
__________________________________________________________________________________________________
activation (Activation)         (None, 512, 512, 8,  0           conv3d[0][0]                     
_________________________________ 2D case (2D-Unet)_________________________________________________________________
conv3d_1 (Conv3D)               (None, 512, 512, 8,  1736        activation[0][0]                 
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 512, 512, 8,  0           conv3d_1[0][0]                   
__________________________________________________________________________________________________
max_pooling3d (MaxPooling3D)    (None, 256, 256, 4,  0           activation_1[0][0]               
__________________________________________________________________________________________________
dropout (Dropout)               (None, 256, 256, 4,  0           max_pooling3d[0][0]              
__________________________________________________________________________________________________
conv3d_transpose (Conv3DTranspo (None, 512, 512, 8,  1736        dropout[0][0]                    
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 512, 512, 8,  0           conv3d_transpose[0][0]           
                                                                 activation_1[0][0]               
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 512, 512, 8,  0           concatenate[0][0]                
__________________________________________________________________________________________________
conv3d_2 (Conv3D)               (None, 512, 512, 8,  3464        dropout_1[0][0]                  
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 512, 512, 8,  0           conv3d_2[0][0]                   
__________________________________________________________________________________________________
conv3d_3 (Conv3D)               (None, 512, 512, 8,  1736        activation_2[0][0]               
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 512, 512, 8,  0           conv3d_3[0][0]                   
__________________________________________________________________________________________________
conv3d_4 (Conv3D)               (None, 512, 512, 8,  9           activation_3[0][0]               
==================================================================================================
Total params: 8,905
Trainable params: 8,905
Non-trainable params: 0
__________________________________________________________________________________________________
```

When using a pooling layer for the down-sampling I get the error below: 
```
Traceback (most recent call last):
  File "/home/st-ai-netanya/Surgical_Theater_AI/Liver_Extraction/test_file.py", line 121, in <module>
    onnx_model = keras2onnx.convert_keras(model, debug_mode=1)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/main.py", line 80, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/parser.py", line 839, in parse_graph
    return _parse_graph_core_v2(
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/parser.py", line 717, in _parse_graph_core_v2
    layer_info, model_ = _parse_nodes_v2(graph, inference_nodeset, input_nodes, keras_node_dict, node,
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/parser.py", line 667, in _parse_nodes_v2
    layer_info = LayerInfo.create(node, layer_key,
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/_parser_tf.py", line 130, in create
    if fstr_list is not None and i_.op.name.find(layer_name) == -1:
TypeError: must be str, not NoneType
```

When replacing the pooling layer with a cropping layer (as can be seen in the commented line) and not using the BatchNormalization layers ("is_batchnorm=False") there is no error. When using BatchNormalization in the model (with the cropping layer) I get the error below:
```
Traceback (most recent call last):
  File "/home/st-ai-netanya/Surgical_Theater_AI/Liver_Extraction/test_file.py", line 121, in <module>
    onnx_model = keras2onnx.convert_keras(model, debug_mode=1)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/main.py", line 83, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/topology.py", line 322, in convert_topology
    cvt(scope, operator, container)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/_tf_ops.py", line 74, in pass_thru_converter
    oopb.add_node(operator.type,
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/onnxconverter_common/oopb.py", line 140, in add_node
    self._container.add_node(op_type, ox_inputs, ox_outputs, op_domain, op_version,
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/keras2onnx/common/interim.py", line 133, in add_node
    node = helper.make_node(op_type, inputs, outputs, **attrs)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/onnx/helper.py", line 108, in make_node
    node.attribute.extend(
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/onnx/helper.py", line 109, in <genexpr>
    make_attribute(key, value)
  File "/home/st-ai-netanya/.local/lib/python3.8/site-packages/onnx/helper.py", line 393, in make_attribute
    raise TypeError(
TypeError: value "" is not valid attribute data type.
```

These errors don't exist while saving a trained keras **2D-Unet** as an ONNX using keras2onnx (using MaxPooling2D).

**Comment by navegeri** [comment]
Problem solved!
Downgrading tensorflow to 2.2.0 (from 2.3.1) solved both issues.
I believe that also installing keras2onnx versio 1.7.1 from the git source would have solved that as well.
