### ISSUE TITLE
yolov3 convert problems

### ISSUE THREAD

**Issue by guapizyq** [onnx/keras-onnx#81]
Traceback (most recent call last):
  File "yolov3.py", line 313, in <module>
    convert_model(YOLO(), 'model_data/yolov3.onnx')
  File "yolov3.py", line 303, in convert_model
    debug_mode=True, custom_op_conversions=_custom_op_handlers)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/main.py", line 92, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/parser.py", line 497, in parse_graph
    return _parse_graph_scope(graph, keras_op_table, topo, top_level, output_names)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/parser.py", line 482, in _parse_graph_scope
    _finalize_const_graph(topology, top_scope, varset)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/parser.py", line 266, in _finalize_const_graph
    _finalize_tf2onnx_op(topology, op_, varset)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/parser.py", line 255, in _finalize_tf2onnx_op
    g = tf2onnx_wrap(topo, subgraph, outputs, varset.target_opset)
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/wrapper.py", line 29, in tf2onnx_wrap
    raise e
  File "/usr/local/lib/python3.5/dist-packages/keras2onnx-1.4.0-py3.5.egg/keras2onnx/wrapper.py", line 23, in tf2onnx_wrap
    output_names=outputs)
  File "/usr/local/lib/python3.5/dist-packages/tf2onnx-1.5.0-py3.5.egg/tf2onnx/tfonnx.py", line 751, in process_tf_graph

**Comment by jiafatom** [comment]
@guapizyq For yolov3 model, you need use the one we provided in model zoo. Please do not use converter code because we have some changes that are not checked in yet.

**Comment by jiafatom** [comment]
@guapizyq We have updated yolov3 conversion code, please pull keras-onnx master and try. Thanks for your patience.
