### ISSUE TITLE
TypeError: 'function' object is not iterable

### ISSUE THREAD

**Issue by scutzhe** [onnx/keras-onnx#87]
ubuntu 16.04
python 3.5
onnx 1.5.0
tf2onnx 04.2
tensorflow-gpu 1.8.0
keras 2.2.4/2.1.5
Traceback (most recent call last):
  File "yolov3.py", line 311, in <module>
    convert_model(YOLO(), 'model_data/yolov3_.onnx')
  File "yolov3.py", line 301, in convert_model
    debug_mode=True, custom_op_conversions=_custom_op_handlers)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/main.py", line 93, in convert_keras
    parse_graph(topology, sess.graph, target_opset, output_names)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/parser.py", line 440, in parse_graph
    return _parse_graph_scope(graph, keras_op_table, topo, top_level, output_names)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/parser.py", line 426, in _parse_graph_scope
    _infer_graph_shape(topology, top_scope, varset)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/parser.py", line 230, in _infer_graph_shape
    _finalize_tf2onnx_op(topology, oop, varset)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/parser.py", line 200, in _finalize_tf2onnx_op
    g = tf2onnx_wrap(topo, subgraph, outputs, varset.target_opset)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/wrapper.py", line 31, in tf2onnx_wrap
    raise e
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/keras2onnx/wrapper.py", line 25, in tf2onnx_wrap
    output_names=outputs)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/tf2onnx/tfonnx.py", line 2446, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "/home/zhex/anaconda3/envs/keras2onnx/lib/python3.5/site-packages/tf2onnx/tfonnx.py", line 2260, in tensorflow_onnx_mapping
    func, args = map_info
TypeError: 'function' object is not iterable

**Comment by jiafatom** [comment]
Please do not use the code in yolov3.py, because there are some changes that are not checked-in.
Use the pretrained yolov3 onnx model [here](https://github.com/onnx/models/tree/master/yolov3).

**Comment by jiafatom** [comment]
@scutzhe We have updated yolov3 conversion code and now users can convert the model by themselves. Please pull latest keras-onnx master and try, thanks for your patience.
