### ISSUE TITLE
TypeError: None has type NoneType, but expected one of: int, long

### ISSUE THREAD

**Issue by ManolacheCristian** [onnx/keras-onnx#94]
Hello, I'm trying to convert a Keras model to ONNX, but unfortunately I get the following error:
```
Traceback (most recent call last):
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/main.py", line 11, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/keras2onnx/main.py", line 95, in convert_keras
    return convert_topology(topology, name, doc_string, target_opset, channel_first_inputs)
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/keras2onnx/topology.py", line 231, in convert_topology
    get_converter(operator.type)(scope, operator, container)
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/keras2onnx/ke2onnx/bidirectional.py", line 217, in convert_bidirectional
    apply_reshape(scope, lstm_y_name, lstm_y_name_fixed, container, desired_shape=[seq_length, 2, -1, hidden_size])
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/onnxconverter_common/onnx_ops.py", line 451, in apply_reshape
    container.add_initializer(desired_shape_name, onnx_proto.TensorProto.INT64, [len(desired_shape)], desired_shape)
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/keras2onnx/common/interim.py", line 202, in add_initializer
    tensor = helper.make_tensor(name, onnx_type, shape, content)
  File "/home/speed-marius/ONNX/Keras2ONNXConverter/venv/lib/python3.6/site-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: None has type NoneType, but expected one of: int, long
```
This is the code:
```
from keras.models import load_model
import keras2onnx
import onnx

model_file_name = "simple_model_256_steps"
model = load_model(model_file_name)

print(model.summary())

# Conversion using keras2onnx
onnx_model = keras2onnx.convert_keras(model, model.name)

# Save ONNX model
onnx_model_file = 'model.onnx'
onnx.save_model(onnx_model, onnx_model_file)
```
This is the model.summary() :
```
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, None)              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, None, 128)         4992      
_________________________________________________________________
bidirectional_1 (Bidirection (None, None, 512)         788480    
_________________________________________________________________
dropout_1 (Dropout)          (None, None, 512)         0         
_________________________________________________________________
dense_1 (Dense)              (None, None, 44)          22572     
=================================================================
Total params: 816,044
Trainable params: 816,044
Non-trainable params: 0
```
I am using:
```
onnx 1.5.0
keras2onnx 2.4.0
keras 2.2.4
```

**Comment by jiafatom** [comment]
Can you please share the model so that we can run?

**Comment by ManolacheCristian** [comment]
Of course, here is a link to the model: https://we.tl/t-oGJGt2MAs5

**Comment by jiafatom** [comment]
@ManolacheCristian I just try to download the link but the file seems deleted. Can you share again? Thanks.

**Comment by ManolacheCristian** [comment]
Certainly, here is a new link: https://we.tl/t-BLmOQrnba4

**Comment by jiafatom** [comment]
@ManolacheCristian  Currently bidirectional conversion does not support dynamic seq_length, batch_size well. Will fix it.

**Comment by jiafatom** [comment]
@ManolacheCristian Can you share your script to generate this model? I see your keras model input, size (?, ?) where seq_length is unknown. How do you construct your keras model? I want to add your case into unit case. Thanks.

**Comment by jiafatom** [comment]
@ManolacheCristian Just checked in the [fix](https://github.com/onnx/keras-onnx/pull/125), it should convert correctly and match keras original model result when `batch_size = 1`. Please pull the latest master and try. For `batch_size > 1`, the result seems mismatch. Created an [issue](https://github.com/onnx/keras-onnx/issues/126) to track that. We will track the issue there if there are no other questions.

**Comment by ManolacheCristian** [comment]
Ok, thank you! Do you still require the script to generate the model?

**Comment by jiafatom** [comment]
I have a unit test [here](https://github.com/onnx/keras-onnx/blob/master/tests/test_layers.py#L781-L790), does it cover your case? If not, welcome to share the script, thanks

**Comment by ManolacheCristian** [comment]
I believe it is similar to "test_Bidirectional_seqlen_none"; here is the link to the script: https://we.tl/t-WGzmGsbFKE (function get_model)

**Comment by jiafatom** [comment]
@ManolacheCristian Thanks, yes it is similar to our unit test, so the unit test covers your case :)
