### ISSUE TITLE
ONNXRuntimeError using the generated Bidirectional-LSTM onnx

### ISSUE THREAD

**Issue by fjfjfan** [onnx/keras-onnx#95]
The code to generate the model:
```
# -*- coding: utf-8 -*-
import time
import math
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, GRU, LSTM, Bidirectional, Dense
from keras import backend as K
import tensorflow as tf
import keras2onnx

# Fix random seed for reproducibility
np.random.seed(3)

data_dim = 4  # input_size
timesteps = 3  # seq_length

# expected input data shape: (batch_size, timesteps, data_dim)
train_input = np.random.uniform(low=-0.5, high=0.5, size=(100, timesteps, data_dim)).astype(np.float32)
train_output = np.random.uniform(low=-0.5, high=0.5, size=(100, 256)).astype(np.float32)

# Number of layer and number of neurons in each layer
num_neur = [128, 128, 128]
# num_neur = [128]
# Training times
epochs = 20
# Batch size
batch_size = 10

# Record time
start_cr_a_fit_net = time.time()
# Create and fit the RNN network
model = Sequential()

for i in range(len(num_neur)):  # multi-layer
    if len(num_neur) == 1:
        model.add(Bidirectional(LSTM(num_neur[i], input_shape=(timesteps, data_dim), unroll=True, recurrent_activation='sigmoid')))
    else:
        if i < len(num_neur) - 1:
            model.add(Bidirectional(LSTM(num_neur[i], input_shape=(timesteps, data_dim), return_sequences=True, unroll=True, recurrent_activation='sigmoid')))
        else:
            model.add(Bidirectional(LSTM(num_neur[i], input_shape=(timesteps, data_dim), unroll=True, recurrent_activation='sigmoid')))


# Compile the neural network
model.compile(loss='mean_squared_error', optimizer='adam')
# Fit the LSTM network
model.fit(train_input, train_output, epochs=epochs, batch_size=batch_size, verbose=0)

# Summary the structure of neural network
model.summary()

end_cr_a_fit_net = time.time() - start_cr_a_fit_net
print('Running time of creating and fitting the LSTM network: %.2f Seconds' % (end_cr_a_fit_net))

print('model.inputs', model.inputs)
print('model.outputs', model.outputs)

test_input = np.random.uniform(low=-0.5, high=0.5, size=(1, timesteps, data_dim)).astype(np.float32)
test_output = model.predict(test_input)

onnx_model = keras2onnx.convert_keras(model, model.name)

import onnx
onnx_filename = "keras_lstm1.onnx"
onnx.save_model(onnx_model, onnx_filename)


K.clear_session()

#####################
# verify
#####################
import onnxruntime as rt


sess = rt.InferenceSession(onnx_filename)
input_name_X = sess.get_inputs()[0].name
label_name_Y = sess.get_outputs()[0].name

pred_rst = sess.run([label_name_Y], {input_name_X: test_input})

```
will get error:
```

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/fjbnu/PycharmProjects/genereate_models/keras_h5_models/lstm_1.py", line 77, in <module>
    sess = rt.InferenceSession(onnx_filename)
  File "/Users/fjbnu/anaconda2/envs/python3.6/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from keras_lstm1.onnx failed:[TypeInferenceError] Invalid attribute perm {2, 0, 1, 3}, input shape = {2, 1, 128}
PyDev console: starting.
```

![image](https://user-images.githubusercontent.com/24930107/58313820-072eea80-7e41-11e9-9a28-b893b3629648.png)

Seems the Transpose Op after the last LSTM has some problem. Thanks!

**Comment by jiafatom** [comment]
@fjfjfan We made some changes on bidirectional recently. I just tried your code and it works. perm here is [1,0,2], rather than [2,0,1,3]. See the picture below. Can you pull latest keras-onnx master and try? Thanks.

![lstm](https://user-images.githubusercontent.com/30608893/59056031-16079b00-884c-11e9-9949-04e1face6acd.png)

**Comment by fjfjfan** [comment]
Thanks a lot, it works, closing the issue.
